// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Models;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250129181330_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "IT & Software Development"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Healthcare & Medicine"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Engineering & Architecture"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Education & Training"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Sales & Marketing"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Customer Service"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Accounting & Finance"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Human Resources"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Construction & Skilled Trades"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Transport & Logistics"
                        },
                        new
                        {
                            Id = 11,
                            Title = "Hospitality & Tourism"
                        },
                        new
                        {
                            Id = 12,
                            Title = "Media & Communications"
                        },
                        new
                        {
                            Id = 13,
                            Title = "Arts & Design"
                        },
                        new
                        {
                            Id = 14,
                            Title = "Legal & Compliance"
                        },
                        new
                        {
                            Id = 15,
                            Title = "Retail & E-commerce"
                        },
                        new
                        {
                            Id = 16,
                            Title = "Manufacturing & Production"
                        },
                        new
                        {
                            Id = 17,
                            Title = "Science & Research"
                        },
                        new
                        {
                            Id = 18,
                            Title = "Public Sector & Government"
                        },
                        new
                        {
                            Id = 19,
                            Title = "Environmental & Agriculture"
                        },
                        new
                        {
                            Id = 20,
                            Title = "Freelancing & Remote Work"
                        });
                });

            modelBuilder.Entity("api.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Banja Luka"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Sarajevo"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Mostar"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Tuzla"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Zenica"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Doboj"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Bijeljina"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Trebinje"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Prijedor"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Gradiška"
                        },
                        new
                        {
                            Id = 11,
                            Title = "Brčko"
                        },
                        new
                        {
                            Id = 12,
                            Title = "Široki Brijeg"
                        },
                        new
                        {
                            Id = 13,
                            Title = "Livno"
                        },
                        new
                        {
                            Id = 14,
                            Title = "Konjic"
                        },
                        new
                        {
                            Id = 15,
                            Title = "Jajce"
                        },
                        new
                        {
                            Id = 16,
                            Title = "Zvornik"
                        },
                        new
                        {
                            Id = 17,
                            Title = "Cazin"
                        },
                        new
                        {
                            Id = 18,
                            Title = "Bihać"
                        },
                        new
                        {
                            Id = 19,
                            Title = "Travnik"
                        },
                        new
                        {
                            Id = 20,
                            Title = "Bugojno"
                        },
                        new
                        {
                            Id = 21,
                            Title = "Goražde"
                        },
                        new
                        {
                            Id = 22,
                            Title = "Foča"
                        },
                        new
                        {
                            Id = 23,
                            Title = "Srebrenica"
                        },
                        new
                        {
                            Id = 24,
                            Title = "Višegrad"
                        },
                        new
                        {
                            Id = 25,
                            Title = "Laktaši"
                        },
                        new
                        {
                            Id = 26,
                            Title = "Nevesinje"
                        },
                        new
                        {
                            Id = 27,
                            Title = "Sanski Most"
                        },
                        new
                        {
                            Id = 28,
                            Title = "Bosanska Krupa"
                        },
                        new
                        {
                            Id = 29,
                            Title = "Kotor Varoš"
                        },
                        new
                        {
                            Id = 30,
                            Title = "Modriča"
                        });
                });

            modelBuilder.Entity("api.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Bosna i Hercegovina"
                        });
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
